///////////////////////////////////////////////////////////
//  classe_classe.cs
//  Implementation of the Class classe
//  Generated by Enterprise Architect
//  Created on:      30-avr.-2026 09:41:52
//  Original author: Oz
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using MySql.Data.MySqlClient;



using Package1;
namespace Package1 {
	public class classe {

		private string adresse_Etablissement;
		private string etablissement;
		private string niveau;
		private string nom_classe;
		private string professeur;
		public Package1.SGBD sgbd;

		public classe(){

		}

		~classe(){

		}

		public void ajouter()
		{
            string query = "INSERT INTO classes (nom_classe, professeur, etablissement, adresse_etablissement, niveau) VALUES (@nom_classe, @professeur, @etablissement, @adresse_etablissement, @niveau)";
            MySqlCommand cmd = new MySqlCommand(query);
            cmd.Parameters.AddWithValue("@nom_classe", nom_classe);
            cmd.Parameters.AddWithValue("@professeur", professeur);
            cmd.Parameters.AddWithValue("@etablissement", etablissement);
            cmd.Parameters.AddWithValue("@adresse_etablissement", adresse_Etablissement);
            cmd.Parameters.AddWithValue("@niveau", niveau);
            cmd.ExecuteNonQuery();

        }

        /// 
        /// <param name="classes"></param>
        public void consulter(string classes){

		}

		public void supprimer(){

		}

	}//end classe

}//end namespace Package1