///////////////////////////////////////////////////////////
//  SGBD.cs
//  Implementation of the Class SGBD
//  Generated by Enterprise Architect
//  Created on:      30-janv.-2026 09:20:45
//  Original author: Utilisateur
///////////////////////////////////////////////////////////

using MySql.Data.MySqlClient;
using Package1;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Text;
using System.Windows;
namespace Package1 {
	public class SGBD {

		private string identifiant;
		private string mdp;
		public Package1.article m_article;
		public Package1.adherent m_adherent;
		private string conString;
		private MySqlConnection con;
		private MySqlCommand cmd;
		private MySqlDataReader reader;

        public SGBD(string connectionString){
			conString = connectionString;
        }

		~SGBD(){

		}

		public void connect()
        {
           con.Open();
        }

		public void deconnect()
        {
            con.Close();
        }

		public void ecrire(string requette)
        {
            con = new MySqlConnection(conString);
            cmd.Connection = con;
            cmd.CommandText = requette;
        }

		/// 
		/// <param name="mdp"></param>
		public string hachage(string mdp){

			return "";
        }

        /// 
        /// <param name="requette_SQL"></param>
        public void prep_req_SQL(string requette_SQL)
        {
			
        }

        public string lire(string requette)
		{
			reader = cmd.ExecuteReader();
			reader.Read();
            return "";
		}


		/// 
		/// <param name="mdp"></param>
		public bool verification_hachage(string mdp)
		{
			return false;
		}

	}//end SGBD

}//end namespace Package1