///////////////////////////////////////////////////////////
//  SGBD.cs
//  Implementation of the Class SGBD
//  Generated by Enterprise Architect
//  Created on:      30-janv.-2026 09:20:45
//  Original author: Utilisateur
///////////////////////////////////////////////////////////

using MySql.Data.MySqlClient;
using Package1;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Text;
using System.Windows;
namespace Package1 {
	public class SGBD {

		private string identifiant;
		private string mdp;
		public Package1.article m_article;
		public Package1.adherent m_adherent;
		private readonly string conString;

		public SGBD(string connectionString){
			conString = connectionString;
        }

		~SGBD(){

		}

		public void connect()
        {
            MySqlConnection connection = new MySqlConnection(conString);
            connection.Open();
        }

		public void deconnect()
        {
            MySqlConnection connection = new MySqlConnection(conString);
            connection.Close();
        }

		public void ecrire()
		{

		}

		/// 
		/// <param name="mdp"></param>
		public string hachage(string mdp){

			return "";
		}

		public void lire()
		{
		}

		/// 
		/// <param name="requette_SQL"></param>
		public void prep_req_SQL(string requette_SQL)
		{
		}

		/// 
		/// <param name="mdp"></param>
		public bool verification_hachage(string mdp)
		{
			return false;
		}

	}//end SGBD

}//end namespace Package1